apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-app-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app-container
        image: nginx:latest
        ports:
        - containerPort: 3000
