apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app-v1
  template:
    metadata:
      labels:
        app: web-app-v1
    spec:
      containers:
      - name: web-app-container
        image: web-app:v1
        ports:
        - containerPort: 3000
